config/routes.rb
Rails.application.routes.draw do
  resources :sale_lines
  resources :sales
  resources :purchase_lines
  resources :purchases
  resources :products
  resources :categories
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/purchase_line.rb
class PurchaseLine < ApplicationRecord
  belongs_to :product
  belongs_to :purchase

  before_validation :calcular_subtotal

  def calcular_subtotal
  	self.subtotal = product.price * quantity
  end
end

app/controllers/purchase_lines_controller.rb
class PurchaseLinesController < ApplicationController
  before_action :set_purchase_line, only: [:show, :edit, :update, :destroy]

  # GET /purchase_lines
  # GET /purchase_lines.json
  def index
    @purchase_lines = PurchaseLine.all
  end

  # GET /purchase_lines/1
  # GET /purchase_lines/1.json
  def show
  end

  # GET /purchase_lines/new
  def new
    @purchase_line = PurchaseLine.new
  end

  # GET /purchase_lines/1/edit
  def edit
  end

  # POST /purchase_lines
  # POST /purchase_lines.json
  def create
    @purchase_line = PurchaseLine.new(purchase_line_params)

    respond_to do |format|
      if @purchase_line.save
        format.html { redirect_to @purchase_line, notice: 'Purchase line was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_line }
      else
        format.html { render :new }
        format.json { render json: @purchase_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_lines/1
  # PATCH/PUT /purchase_lines/1.json
  def update
    respond_to do |format|
      if @purchase_line.update(purchase_line_params)
        format.html { redirect_to @purchase_line, notice: 'Purchase line was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_line }
      else
        format.html { render :edit }
        format.json { render json: @purchase_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_lines/1
  # DELETE /purchase_lines/1.json
  def destroy
    @purchase_line.destroy
    respond_to do |format|
      format.html { redirect_to purchase_lines_url, notice: 'Purchase line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_line
      @purchase_line = PurchaseLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_line_params
      params.require(:purchase_line).permit(:subtotal, :product_id, :purchase_id, :quantity, purchase_lines_attributes:[:product_id, :quantity])
    end
end

app/helpers/purchase_lines_helper.rb
module PurchaseLinesHelper
end

app/views/purchase_lines/_form.html.erb
<%= form_with(model: purchase_line, local: true) do |form| %>
  <% if purchase_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_line.errors.count, "error") %> prohibited this purchase_line from being saved:</h2>

      <ul>
      <% purchase_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.text_field :subtotal %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :purchase_id %>
    <%= form.text_field :purchase_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_lines/edit.html.erb
<h1>Editing Purchase Line</h1>

<%= render 'form', purchase_line: @purchase_line %>

<%= link_to 'Show', @purchase_line %> |
<%= link_to 'Back', purchase_lines_path %>

app/views/purchase_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchase Lines</h1>

<table>
  <thead>
    <tr>
      <th>Subtotal</th>
      <th>Product</th>
      <th>Purchase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_lines.each do |purchase_line| %>
      <tr>
        <td><%= purchase_line.subtotal %></td>
        <td><%= purchase_line.product %></td>
        <td><%= purchase_line.purchase %></td>
        <td><%= link_to 'Show', purchase_line %></td>
        <td><%= link_to 'Edit', edit_purchase_line_path(purchase_line) %></td>
        <td><%= link_to 'Destroy', purchase_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase Line', new_purchase_line_path %>

app/views/purchase_lines/new.html.erb
<h1>New Purchase Line</h1>

<%= render 'form', purchase_line: @purchase_line %>

<%= link_to 'Back', purchase_lines_path %>

app/views/purchase_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subtotal:</strong>
  <%= @purchase_line.subtotal %>
</p>

<p>
  <strong>Product:</strong>
  <%= @purchase_line.product %>
</p>

<p>
  <strong>Purchase:</strong>
  <%= @purchase_line.purchase %>
</p>

<%= link_to 'Edit', edit_purchase_line_path(@purchase_line) %> |
<%= link_to 'Back', purchase_lines_path %>